# Generated by Django 6.1 on 2026-09-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_trending_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, default='India Post', help_text='Courier service or Post Office branch', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing / Packed'), ('Dispatched', 'Dispatched via Post Office'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Processing', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='India Post / Speed Post consignment tracking number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_notes',
            field=models.CharField(blank=True, help_text='Dispatch notes (e.g. Dispatched from Karuvissery Post Office)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
