# Generated by Django 6.1 on 2026-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_carrier_order_shipping_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery charge based on destination and products', max_digits=10),
        ),
    ]
