# Generated by Django 6.1 on 2026-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='City / District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_region',
            field=models.CharField(blank=True, default='kerala', help_text='Inside Kerala vs Outside Kerala', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, help_text='Postal PIN Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='City / District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, help_text='Postal PIN Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
    ]
