# Generated by Django 6.1 on 2026-09-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_city_order_delivery_region_order_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Photo 2 (optional)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2_url',
            field=models.URLField(blank=True, help_text='Direct link to Photo 2 (optional)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Photo 3 (optional)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3_url',
            field=models.URLField(blank=True, help_text='Direct link to Photo 3 (optional)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Photo 4 (optional)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4_url',
            field=models.URLField(blank=True, help_text='Direct link to Photo 4 (optional)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo 1 - Main Cover Image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to Photo 1 (optional)', max_length=1000, null=True),
        ),
    ]
