# Generated by Django 6.1 on 2026-09-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image_2_product_image_2_url_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique admin/shipping code visible only to admin (e.g. 100, 101)', max_length=50, null=True, unique=True),
        ),
    ]
