# Generated by Django 6.1 on 2026-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_admin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby Landmark (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Alternate Phone Number 2 (Optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby Landmark (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Alternate Phone Number 2 (Optional)', max_length=20, null=True),
        ),
    ]
