# Generated by Django 6.1 on 2026-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_district_order_landmark_order_phone_number_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, help_text='Razorpay Refund ID if refunded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Refunded amount in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_notes',
            field=models.TextField(blank=True, help_text='Refund details or reason', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
