# Generated by Django 6.1 on 2026-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_razorpay_refund_id_order_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment Link ID for QR flow', max_length=100, null=True),
        ),
    ]
