services:
  - type: web
    name: aashas-store
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn aashas_store.wsgi:application"
    domains:
      - ashasstore.in
      - www.ashasstore.in
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_aymQ0eRnjJt4@ep-lingering-pine-b4lebot7-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        value: "owtliihd"
      - key: CLOUDINARY_API_KEY
        value: "634465815929627"
      - key: CLOUDINARY_API_SECRET
        value: "MfP1G3e-dncWMBeKwoSoIx7IGfk"
      - key: RAZORPAY_KEY_ID
        value: "rzp_live_Tck3w9pvGwRGOY"
      - key: RAZORPAY_KEY_SECRET
        value: "uct85ngbFuvyRgdqhGYDFdG4"
