from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('rings/', views.category_detail, {'slug': 'rings'}, name='rings_page'),
    path('ring.html', views.category_detail, {'slug': 'rings'}, name='ring_html'),
    path('rings.html', views.category_detail, {'slug': 'rings'}, name='rings_html'),
    path('shades/', views.category_detail, {'slug': 'shades'}, name='shades_page'),
    path('chains/', views.category_detail, {'slug': 'chains'}, name='chains_page'),
    path('watches/', views.category_detail, {'slug': 'watches'}, name='watches_page'),
    path('bracelets/', views.category_detail, {'slug': 'bracelets'}, name='bracelets_page'),
    path('caps/', views.category_detail, {'slug': 'caps'}, name='caps_page'),
    path('belts/', views.category_detail, {'slug': 'belts'}, name='belts_page'),
    path('ping/', views.ping_view, name='ping'),
    path('health/', views.ping_view, name='health'),
    path('cron/', views.ping_view, name='cron'),
    path('robots.txt', views.robots_txt_view, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml_view, name='sitemap_xml'),
    path('favicon.ico', views.favicon_view, name='favicon_ico'),
    path('google44f351804c9055d3.html', views.google_verification_view, name='google_verification'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('verify-payment/', views.payment_verify, name='payment_verify'),
    path('api/razorpay-webhook/', views.razorpay_webhook, name='razorpay_webhook'),
    path('contact-submit/', views.contact_submit, name='contact_submit'),

    # Admin portal endpoints
    path('adminpp/', views.adminpp_dashboard, name='adminpp_dashboard'),
    path('adminpp/orders/', views.adminpp_orders, name='adminpp_orders'),
    path('adminpp/order/delete/<int:order_id>/', views.adminpp_order_delete, name='adminpp_order_delete'),
    path('adminpp/orders/clear-all/', views.adminpp_clear_all_orders, name='adminpp_clear_all_orders'),
    path('adminpp/order/update-tracking/<int:order_id>/', views.adminpp_update_tracking, name='adminpp_update_tracking'),
    path('adminpp/category/add/', views.category_create_or_edit, name='category_add'),
    path('adminpp/category/edit/<int:pk>/', views.category_create_or_edit, name='category_edit'),
    path('adminpp/category/delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('adminpp/product/add/', views.product_create_or_edit, name='product_add'),
    path('adminpp/product/edit/<int:pk>/', views.product_create_or_edit, name='product_edit'),
    path('adminpp/product/delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('adminpp/product/toggle-trending/<int:pk>/', views.product_toggle_trending, name='product_toggle_trending'),
    path('adminpp/inquiry/delete/<int:pk>/', views.inquiry_delete, name='inquiry_delete'),
]